/**
 * TaskChain types for AMA.
 * Defines the structure of a task chain generated by LLM and executed by CLINE.
 */

/**
 * A single step in a task chain.
 */
export interface TaskChainStep {
    /** Unique identifier for this step (e.g., "step1", "step2") */
    id: string;
    /** The action to perform (e.g., "git_pull", "npm_build", "deploy_render") */
    action: string;
    /** Human-readable description of what this step does */
    description?: string;
    /** Arbitrary parameters for the action */
    [key: string]: any;
}

/**
 * A complete task chain — an ordered list of steps to execute sequentially.
 */
export type TaskChain = TaskChainStep[];

/**
 * Execution status of a single step.
 */
export type StepStatus = 'pending' | 'running' | 'success' | 'failed' | 'skipped';

/**
 * Runtime state of a step during execution.
 */
export interface StepExecutionState {
    step: TaskChainStep;
    status: StepStatus;
    startedAt?: string;
    completedAt?: string;
    output?: string;
    error?: string;
    retryCount: number;
}

/**
 * Overall execution state of a task chain.
 */
export interface TaskChainExecutionState {
    chain: TaskChain;
    steps: StepExecutionState[];
    currentStepIndex: number;
    isRunning: boolean;
    isAborted: boolean;
    startedAt?: string;
    completedAt?: string;
    totalSteps: number;
    completedSteps: number;
    failedSteps: number;
}

/**
 * Configuration for task chain execution.
 */
export interface TaskChainExecutionConfig {
    /** Max retries per step (default: 0 = no retry) */
    maxRetriesPerStep: number;
    /** Delay in ms between retries (default: 2000) */
    retryDelayMs: number;
    /** Whether to abort on first failure (default: true) */
    abortOnFailure: boolean;
    /** Whether to log each step's output to the log view (default: true) */
    logOutput: boolean;
}
